import type {ActionRecordRaw} from "@/types/action";

export const staticActions = [
    {
        id: "main-data-model",
        pId: "",
        actionId: "mainDataModel",
        title: "主数据建模",
        type: MenuPageType.MENU,
        sort: 1,
        showInMenu: ShowInMenuType.SHOW,
        children: [{
            id: "data-model",
            pId: "main-data-model",
            actionId: "dataModel",
            title: "数据建模",
            type: MenuPageType.MENU,
            sort: 11,
            showInMenu: ShowInMenuType.SHOW,
            children: [{
                id: "model-list",
                pId: "data-model",
                actionId: "modelList",
                title: "模型列表",
                type: MenuPageType.PAGE,
                sort: 111,
                showInMenu: ShowInMenuType.HIDE,
                url: "/data-model",
                component: "main-data-model/data-model/Index.vue",
            }, {
                id: "model-sett",
                pId: "data-model",
                actionId: "modelEditor",
                title: "模型配置",
                type: MenuPageType.PAGE,
                sort: 111,
                showInMenu: ShowInMenuType.HIDE,
                url: "/data-model/:modelId",
                component: "main-data-model/data-model/ModelEditor.vue",
            }],
        }, {
            id: "view-management",
            pId: "main-data-model",
            actionId: "viewMng",
            title: "视图管理",
            type: MenuPageType.MENU,
            url: "",
            sort: 12,
            showInMenu: ShowInMenuType.SHOW,
            children: [{
                id: "view-list",
                pId: "view-management",
                actionId: "viewList",
                title: "视图列表",
                type: MenuPageType.PAGE,
                sort: 121,
                showInMenu: ShowInMenuType.HIDE,
                url: "/view-management",
                component: "main-data-model/view-management/Index.vue",
            }, {
                id: "view-editor",
                pId: "view-management",
                actionId: "viewEditor",
                title: "新增视图",
                type: MenuPageType.PAGE,
                sort: 121,
                showInMenu: ShowInMenuType.HIDE,
                url: "/view-management/add",
                component: "main-data-model/view-management/ViewEditor.vue",
            }, {
                id: "edit-view",
                pId: "view-management",
                actionId: "editView",
                title: "编辑视图",
                type: MenuPageType.PAGE,
                sort: 11,
                showInMenu: ShowInMenuType.HIDE,
                url: "/view-management/edit/:viewId",
                component: "main-data-model/view-management/ViewEditor.vue",
            }],
        }],
    }, {
        id: "main-data-management",
        pId: "",
        actionId: "mainDataMng",
        title: "主数据管理",
        type: MenuPageType.PAGE,
        sort: 2,
        showInMenu: ShowInMenuType.SHOW,
        url: "/main-data-management",
    }, {
        id: "data-interface",
        pId: "",
        actionId: "interface",
        title: "数据接口",
        type: MenuPageType.MENU,
        sort: 3,
        showInMenu: ShowInMenuType.SHOW,
        children: [{
            id: "interface-setting",
            pId: "interface",
            actionId: "intfSett",
            title: "接口配置",
            type: MenuPageType.PAGE,
            sort: 31,
            showInMenu: ShowInMenuType.SHOW,
            url: "/interface-setting",
            component: "",
        }, {
            id: "interface-log",
            pId: "interface",
            actionId: "intfLog",
            title: "接口日志",
            type: MenuPageType.PAGE,
            sort: 32,
            showInMenu: ShowInMenuType.SHOW,
            url: "/interface-log",
            component: "",
        }],
    }, {
        id: "help-center",
        pId: "",
        actionId: "helpCenter",
        title: "帮助中心",
        type: MenuPageType.PAGE,
        sort: 4,
        showInMenu: ShowInMenuType.SHOW,
        url: "/help-center",
        component: "",
    }, {
        id: "1536643442430447616",
        pId: "",
        actionId: "SysMng",
        title: "系统管理",
        type: MenuPageType.MENU,
        sort: 9,
        showInMenu: ShowInMenuType.SHOW,
        children: [
            {
                id: "licence",
                pId: "1536643442430447616",
                actionId: "licence",
                title: "licence授权",
                type: MenuPageType.PAGE,
                sort: 90,
                showInMenu: ShowInMenuType.SHOW,
                url: "/license",
                component: "",
            },
            {
                id: "1536652592875048960",
                pId: "1536652503813197824",
                actionId: "UserMng",
                title: "用户管理",
                type: MenuPageType.PAGE,
                sort: 91,
                showInMenu: ShowInMenuType.SHOW,
                url: "/user-management",
                // component: "settings/UserManagement",
            },
            {
                id: "1536652666153734144",
                pId: "1536652503813197824",
                actionId: "RoleMng",
                title: "角色管理",
                type: MenuPageType.PAGE,
                sort: 92,
                showInMenu: ShowInMenuType.SHOW,
                url: "/role-management",
                // component: "settings/RoleManagement",
            },
            {
                id: "1536652853853032448",
                pId: "1536652503813197824",
                actionId: "MenuMng",
                title: "菜单管理",
                type: MenuPageType.PAGE,
                sort: 92,
                showInMenu: ShowInMenuType.SHOW,
                url: "/menu-management",
                // component: "settings/MenuManagement",
            },
            {
                id: "1536652773624385536",
                pId: "1536652503813197824",
                actionId: "PermMng",
                title: "权限管理",
                type: MenuPageType.PAGE,
                sort: 94,
                showInMenu: ShowInMenuType.SHOW,
                url: "/permission-management",
                // component: "settings/PermissionManagement",
            },
            {
                id: "1536652915467358208",
                pId: "1536652503813197824",
                actionId: "OrgMng",
                title: "组织机构管理",
                type: MenuPageType.PAGE,
                sort: 95,
                showInMenu: ShowInMenuType.SHOW,
                url: "/organization-management",
                // component: "settings/OrganizationManagement",
            },
            {
                id: "1536653005456150528",
                pId: "1536652503813197824",
                actionId: "PwdMng",
                title: "密码修改",
                type: MenuPageType.PAGE,
                sort: 96,
                showInMenu: ShowInMenuType.SHOW,
                url: "/password-management",
                // component: "settings/PasswordManagement",
            }
        ],
    }
] as ActionRecordRaw[];
